### Kaggle Competition: Linking Writing Processes to Writing Quality -                                                                       https://www.kaggle.com/competitions/linking-writing-processes-to-writing-quality/overview

### Configuration

In [ ]:
%pip install ydata-profiling

In [ ]:
import pandas as pd
import numpy as np
from ydata_profiling import ProfileReport
import matplotlib.pyplot as plt

%matplotlib inline

### Data Loading

In [ ]:
df = pd.read_csv('train_logs.csv')
test_df = pd.read_csv('test_logs.csv')
df_scores = pd.read_csv('train_scores.csv')
sample_submission = pd.read_csv('sample_submission.csv')

### Preliminary Data Analysis

### Data Size

* Number of sources (files, tables)
* Number of records (rows)
* Number of features (columns)
* Does the number match expectations?

In [ ]:
df.shape

In [ ]:
test_df.shape

In [ ]:
df_scores.shape

In [ ]:
sample_submission.shape

In [27]:
sample_submission

         id  score
0  0000aaaa    1.0
1  2222bbbb    2.0
2  4444cccc    3.0

In [28]:
test_df

,id,event_id,down_time,up_time,action_time,activity,down_event,up_event,text_change,cursor_position,word_count
0,0000aaaa,1,338433,338518,85,Input,Space,Space,,0,0
1,0000aaaa,2,760073,760160,87,Input,Space,Space,,1,0
2,2222bbbb,1,711956,712023,67,Input,q,q,q,0,1
3,2222bbbb,2,290502,290548,46,Input,q,q,q,1,1
4,4444cccc,1,635547,635641,94,Input,Space,Space,,0,0
5,4444cccc,2,184996,185052,56,Input,q,q,q,1,1

### Manual Review of Examples - Checking Different Sortings

In [29]:
df.head()

,id,event_id,down_time,up_time,action_time,activity,down_event,up_event,text_change,cursor_position,word_count
0,001519c8,1,4526,4557,31,Nonproduction,Leftclick,Leftclick,NoChange,0,0
1,001519c8,2,4558,4962,404,Nonproduction,Leftclick,Leftclick,NoChange,0,0
2,001519c8,3,106571,106571,0,Nonproduction,Shift,Shift,NoChange,0,0
3,001519c8,4,106686,106777,91,Input,q,q,q,1,1
4,001519c8,5,107196,107323,127,Input,q,q,q,2,1

In [30]:
df.tail()

,id,event_id,down_time,up_time,action_time,activity,down_event,up_event,text_change,cursor_position,word_count
8405893,fff05981,3615,2063944,2064440,496,Nonproduction,Leftclick,Leftclick,NoChange,1031,240
8405894,fff05981,3616,2064497,2064497,0,Nonproduction,Shift,Shift,NoChange,1031,240
8405895,fff05981,3617,2064657,2064765,108,Replace,q,q,q => q,1031,240
8405896,fff05981,3618,2069186,2069259,73,Nonproduction,Leftclick,Leftclick,NoChange,1028,240
8405897,fff05981,3619,2070065,2070133,68,Input,.,.,.,1029,240

### Checking Types

* Numeric columns
* Boolean columns
* Categorical columns
* Text columns
* Consistency in missing value indicators: NULL / empty string

In [ ]:
profile = ProfileReport (df, title="Profiling Report")